spring:
  ldap:
    # urls: ldap://localhost:12345
    # base: dc=memorynotfound,dc=com
    # username: uid=admin
    # password: secret
   embedded:
      base-dn: dc=telino,dc=com
      credential:
        username: uid=admin
        password: test
      ldif: classpath:schema.ldif
      port: 12345
      validation:
        enabled: false
#  data:
#    ldap:
#      repositories:
#        enabled: true
        
management:
  server:
    port: 8081
  endpoints:
    jmx:
      domain: com.telino.myapp
      unique-names: true
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
  metrics:
    web:
      server:
        auto-time-requests: true
      
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
  