server:
  port: 9999
  servlet:
    context-path: /client
security:
  oauth2:
    client:
      client-id: telino
      client-secret: Telino_2018
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/me