server:
  port: 8082
  servlet: 
    context-path: /ui
    session:
      cookie:
        name: UISESSION
        
security:
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      tokenName: oauth_token
    resource:
      userInfoUri: http://localhost:8081/auth/users/me
      
spring:
  thymeleaf:
    cache: false